stages:
  - lint
  - build
  - test
  - publish

default:
  image: r-harbor.smhi.se/foluft/python:3.9-rh8-mini
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .cache

variables:
  PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip

check-manifest:
  stage: lint
  image: r-harbor.smhi.se/foluft/pre-commit:2-py39
  before_script:
    - python -m pip install "check-manifest==0.48"
  script:
    - check-manifest

pre-commit:
  stage: lint
  image: r-harbor.smhi.se/foluft/pre-commit:2-py39
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - pre-commit run -a

build:
  stage: build
  image: r-harbor.smhi.se/foluft/python:3.9-build-rh8
  before_script:
    - python -m pip install "cython~=0.29.32" "setuptools~=65.5.0"
  script:
    - RASTAFARI_USE_CYTHON=1 python -m build --no-isolation
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

test:
  stage: test
  before_script:
    - python -m pip install -r test-requirements.txt
    - python -m pip install --find-links dist/ --no-deps --no-index rastafari
  script:
    - pytest --cov --junit-xml=junit.xml
  artifacts:
    reports:
      junit: junit.xml
  coverage: /^TOTAL.*\s(\d+)%$/

publish:
  stage: publish
  before_script:
    - python -m pip install "twine~=4.0.1"
  script:
    - twine check dist/*
    - twine upload --non-interactive dist/*
  only:
    - tags
