[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = [
  ".gitlab-ci.yml",
  "src/rastafari/*.c",
]

[tool.coverage.run]
source = ["rastafari"]
branch = true

[tool.pytest.ini_options]
filterwarnings = ["error"]
