name: Build
on:
  push:
    tags:        
      - v*
  workflow_dispatch:
  
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] 

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ENVIRONMENT: RASTAFARI_USE_CYTHON=1
        with:
           package-dir: .
           output-dir: wheelhouse
           config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}${{ github.sha }}
          path: ./wheelhouse/*.whl
