name: Build
on:
  push:
    tags:        
      - v*
  workflow_dispatch:
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Set CIBW_PLATFORM (Linux)
        if: matrix.os == 'ubuntu-20.04'
        run: echo "CIBW_PLATFORM=linux" >> $GITHUB_ENV

      - name: Set CIBW_PLATFORM (Windows)
        if: matrix.os == 'windows-2022'
        run: echo "CIBW_PLATFORM=windows" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Set CIBW_PLATFORM (macOS)
        if: matrix.os == 'macos-11'
        run: echo "CIBW_PLATFORM=macos" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ENVIRONMENT: RASTAFARI_USE_CYTHON=1
        with:
           package-dir: .
           output-dir: wheelhouse
           config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
