name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-check:
    name: Pre-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit check-manifest

      - name: Run pre-commit checks
        run: python -m pre_commit run --all-files

      - name: Check-manifest
        run: check-manifest

  test:
    name: Test (Python ${{ matrix.python-version }})
    needs:
      - pre-check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]"

      - name: Lint
        run: python -m mypy .

      - name: Run tests
        run: python -m pytest --cov=rastafari --junit-xml=junit.xml tests/

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}       # run this step even if previous step failed
        with:
          name: test-results
          path: junit.xml
          reporter: jest-junit
